apiVersion: skaffold/v1
kind: Config
metadata:
  name: andromeda
build:
  artifacts:
    - image: collector
      jib:
        project: collector
    - image: aggregator
      jib:
        project: aggregator
    - image: web
      context: web

deploy:
  kustomize: {}

profiles:
  - name: example
    build:
      artifacts:
        - image: flag
          context: ./platform/flag-example
    deploy:
      kustomize:
        path: ./platform/