apiVersion: skaffold/v1
kind: Config
metadata:
  name: andromeda
build:
  artifacts:
    - image: collector
      jib:
        project: collector
    - image: aggregator
      jib:
        project: aggregator
deploy:
  kustomize: {}