apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yaml

patchesStrategicMerge:
  - deployment-config.yaml

configMapGenerator:
  - name: web-config
    files:
      - config.js