spring:
  profiles:
    active:
      - global
      - cluster
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, prometheus