global:
  canary:
    enabled: true
#   Labels used to determine if a pod is marked as a canary
#   These labels are also explicitly not selected for normal deployments if canaries are enabled.
    selector:
      variant: canary

  teams:
    - name: teamName
      applications:
        - name: web-frontend
          prefix: webApp
          selector:
            type: frontend
        - name: backend-application
          prefix: webApp
          selector:
            type: backend
          deployment: backend-app-container
        - name: redis-for-backend
          prefix: redis
          selector:
            app: app
          statefulSet: redis
    - name: andromeda
      applications:
        - name: collector
          prefix: andromeda
#         selector is defaulted to 'app = application name' - in this case app=collector
#         The type of controller can be specified and must be set to the container name
#         An unset controller:container config is defaulted to a deployment and to the first container