global:
  canary:
    enabled: true
    selector:
      variant: canary
  teams:
    - name: andromeda
      applications:
        - name: collector
          prefix: andromeda
        - name: aggregator
          prefix: andromeda
        - name: web
          prefix: andromeda
    - name: galaxy
      applications:
        - name: nginx
          prefix: nginx
        - name: flag
          prefix: flag
        - name: liveness
          prefix: liveness
          selector:
            testing: liveness
            willFail: "true"