global:
  canary:
    enabled: true
    selector:
      variant: canary
  teams:
    - name: andromeda
      applications:
        - name: collector
          prefix: andromeda
        - name: aggregator
          prefix: andromeda
        - name: web
          prefix: andromeda