apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - serviceaccount.yaml
  - roles.yaml
patchesStrategicMerge:
  - deployment-config.yaml
  - deployment-service-acccount-patch.yaml
configMapGenerator:
  - name: collector-config
    files:
      - application-global-dev.yaml
      - application-cluster-dev.yaml