apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: andromeda-dev
resources:
  - ../base
  - namespace.yml
  - serviceaccount.yaml
  - roles.yaml
patchesStrategicMerge:
  - deployment-env-patch.yaml
  - deployment-service-acccount-patch.yaml