apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  "igiari.net/should_be_scraped": "true"
resources:
  - ../base
  - prometheus/prometheus-deployment.yaml
  - prometheus/prometheus-service.yaml
  - prometheus/prometheus-ingress.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus/prometheus.yml
patchesStrategicMerge:
  - deployment-env-patch.yaml