spring:
  profiles:
    active:
      - local
  http:
    converters:
      preferred-json-mapper: gson
server:
  port: 9090
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
